Repository Spirik/GEM, pull requests merged in 2025-03, with the labels that each got.

#116 Non-interactive Label menu item
  README.md
  keywords.txt
  src/GEM.cpp
  src/GEMItem.cpp
  src/GEMItem.h
  src/GEM_adafruit_gfx.cpp
  src/GEM_u8g2.cpp
Labels: enhancement

#127 AGFX version sprite size bug fix; Loop option for selects/spinners; Optional title for GEMPage constructor
  README.md
  keywords.txt
  src/GEM.cpp
  src/GEMPage.h
  src/GEMSelect.cpp
  src/GEMSelect.h
  src/GEMSpinner.cpp
  src/GEMSpinner.h
  src/GEM_adafruit_gfx.cpp
  src/GEM_adafruit_gfx.h
  src/GEM_u8g2.cpp
  src/constants.h
Labels: bug, enhancement

#117 add platformio installation instructions
  README.md
Labels: documentation
